### ISSUE TITLE
Upgrade problem

### ISSUE THREAD

**Issue by newsjunkie247** [mozilla-rally/rally#407]
I had an older version of the extension and had been participating in several of the studies but since upgrading I can't seem to join those other studies anymore other than Attention Stream.

**Comment by aaga** [comment]
Hi @newsjunkie247, thanks for being a Rally contributor! (I'm one of the engineers on the team)

We're working on communicating this better to our users, but: by using our new experience and enrolling in the Attention Stream, you're actually _automatically_ contributing to some of those existing studies. We made this change so that from now on, you only need to install **one extension** to contribute to multiple studies. So if you see that green check mark ✅ on https://members.rally.mozilla.org/, you're good to go! And you'll also notice that we've renamed the extension from "Attention Stream" to "Mozilla Rally", to reflect the fact that this one extension is for multiple studies.

Expect to see more from us soon about the impact your data contributions are having 👀. Thank you for reaching out and being a part of the Rally community!
