### ISSUE TITLE
Share my Impact

### ISSUE THREAD

**Issue by than-mozilla** [mozilla-rally/rally#415]
## As a Rally user...

I want to understand my impact and be able to share it with my social network, inviting them to contribute as well

## Hypothesis
Users want to show off their impact, and invite others to join.

## Measures
* For the onboarding-based share card, we can measure share button clicks. What is a meaningful number of users who land on the homepage and click a share link?
* For the extension-based share, similarly, we can measure share button clicks. What is a meaningful number of users who see the doorhanger and click a share link?
* Secondary measure is measuring visits resulting from the shares.

**Comment by compzilla** [comment]
I'm curious about UTM codes and would love to talk this thru with others. Will it be the same UTM code for all shares? Will it be a different UTM code if someone shares on Twitter vs. FB vs. etc.? (For later version: Can UTM codes be autogenerated/personalized - this is when gamification could come in. If x ppl join from your share, we'll send you Rally swag...)

**Comment by rhelmer** [comment]
> Will it be the same UTM code for all shares?

I think for the initial version yes, but we can personalize.

> Will it be a different UTM code if someone shares on Twitter vs. FB vs. etc.?

At least one of the codes should be different here, generally `source=twitter`, `medium=social` or something along those lines.

> For later version: Can UTM codes be autogenerated/personalized - this is when gamification could come in. If x ppl join from your share, we'll send you Rally swag...)

We can, but since this makes it potentially personally identifiable, we should create a random UUID just for this purpose (could call it a "share ID"). This is what we've done in the past for similar situations where we're passing things in URLs like the old "deletion ID" from the core add-on. This is [what Google suggests as well](https://support.google.com/google-ads/answer/6389382?hl=en).

We'd make the link between the share ID and the actual user in our system. Since the user is consciously choosing to share this with the world I think it makes this easier to reason about :) The point of the indirection though is so we don't have URLs with email addresses or names or anything like that floating around out there.

**Comment by marniepw** [comment]
Closing as part of Rally wind down.
